**Crear la base de datos** local con la biblioteca SQLAlchemy.

Escribir los datos del archivo CSV en esta base de datos local.

**Realizar tres actualizaciones** en la base de datos:

**Actualizar el registro del cliente ID 6840104** cuyo rendimiento anual cambió a 300000.

**Eliminar el registro de cliente ID 5008809**, ya que esta persona ya no tiene cuenta en la institución financiera.

**Crear un nuevo registro de cliente** siguiendo las especificaciones a continuación:

- ID_cliente: 6850985
- Edad: 33
- Grado_estudio: Doctorado
- Estado_civil: Soltero
- Tamaño_familia: 1
- Categoria_de_renta: Empleado
- Ocupacion: TI
- Años_empleado: 2
- Rendimiento_anual: 290000
- Tiene_carro: 0
- Vivienda: Casa/Departamento propio

**Consejo importante:** Para agregar un nuevo cliente a la tabla, use la cláusula INSERT INTO seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula VALUES y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

Usted es responsable de crear una base de datos local de clientes para una institución financiera.

Disponemos del archivo CSV con los datos de los clientes.

https://github.com/alura-es-cursos/1980-Pandas_IO/raw/clientes_banco/clientes_banco.csv.zip

In [1]:
#LIBRERIAS PARA UTILIZAR EL BANCO DE DATOS SQL

import sqlalchemy

from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [2]:
#UTILIZAR EL MOTOR DE BANCO DE DATOS INCLUIDO EN GOOGLE COLAB QUE SE EJECUTA EN LA MEMORIA LOCAL

engine = create_engine('sqlite:///:memory:')

In [3]:
#IMPORTAR ARCHIVO CSV

import pandas as pd

archivo = 'clientes_banco.csv'

datos = pd.read_csv(archivo)

datos.head(5)

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

In [4]:
#CREAR UNA TABLA EN SQLITE Y EXPORTAR LOS REGISTROS DEL CSV

datos.to_sql('clientes', engine, index=False)

438463

In [6]:
# UTILIZAR EL METODO inspect PARA VERIFICAR LAS TABLAS CREADAS

inspector = inspect(engine)

print(inspector.get_table_names())

['clientes']

In [7]:
#CREAR UNA CONSULTA SQL A LA TABLA CLIENTES

from sqlite3.dbapi2 import connect

query = 'SELECT * FROM clientes'

In [8]:
#EJECUTAR LA CONEXION A SQLITE Y REALIZAR LA CONSULTA CREADA ANTERIORMENTE

clientes = pd.read_sql(sql=text(query), con = engine.connect())

clientes

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [9]:
#Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000

query = 'UPDATE clientes SET Rendimiento_anual = 300000 WHERE ID_Cliente = 6840104'

try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('#Registros actualizado: ', r_set.rowcount)

#Registros actualizado:  1

In [13]:
#VERIFICAR SI SE ACTUALIZO

query = 'SELECT * FROM clientes'
clientes = pd.read_sql(sql=text(query), con = engine.connect())
clientes

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,300000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [14]:
#Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.

from sqlalchemy.exc import SQLAlchemyError

query = 'DELETE FROM clientes WHERE ID_Cliente = 5008809'

try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('#Registros borrados: ', r_set.rowcount)

#Registros borrados:  1

In [15]:
#VERIFICAR SI SE ELIMINO

query = 'SELECT * FROM clientes'
clientes = pd.read_sql(sql=text(query), con = engine.connect())
clientes

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,300000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:

- ID_cliente: 6850985
- Edad: 33
- Grado_estudio: Doctorado
- Estado_civil: Soltero
- Tamaño_familia: 1
- Categoria_de_renta: Empleado
- Ocupacion: TI
- Años_empleado: 2
- Rendimiento_anual: 290000
- Tiene_carro: 0
- Vivienda: Casa/Departamento propio

**Consejo importante:** Para agregar un nuevo cliente a la tabla, use la cláusula INSERT INTO seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula VALUES y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

In [16]:
#AGREGAR NUEVO REGISTRO

query = 'INSERT INTO \
        clientes(ID_cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda) \
        VALUES(6850985,33,"Doctorado","Soltero",1,"Empleado","TI",2,290000,0,"Casa/Departamento propio")'

try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print('#Registros agregados: ', r_set.rowcount)

#Registros agregados:  1

In [17]:
#CONSULTAR REGISTRO AGREGADO

query = 'SELECT * FROM clientes WHERE ID_cliente=6850985'
clientes = pd.read_sql(sql=text(query), con = engine.connect())
clientes

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,6850985,33,Doctorado,Soltero,1,Empleado,TI,2,290000.0,0,Casa/Departamento propio